export const INVITADO = 'INVITADO';
export const VENDEDOR = 'VENDEDOR';
export const ADMINISTRADOR = 'ADMINISTRADOR';

export const ALL_ROLES = {
    [INVITADO]: INVITADO,
    [VENDEDOR]: VENDEDOR,
    [ADMINISTRADOR]: ADMINISTRADOR,
};